DROP TABLE bankstatements IF EXISTS;
DROP TABLE accounts IF EXISTS;
DROP TABLE users IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE global_seq AS INTEGER START WITH 100000;

CREATE TABLE users
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name             VARCHAR(255)            NOT NULL
);

CREATE TABLE accounts
(
    id          INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    number    INT          NOT NULL,
    registered   TIMESTAMP  DEFAULT now()   NOT NULL,
    description VARCHAR(255) NOT NULL,
    typeCurrency VARCHAR(255) NOT NULL,
    value     DOUBLE      NOT NULL,
    user_id     INTEGER      NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX accounts_unique_user_number_idx
    ON accounts (user_id, number);

CREATE TABLE bankstatements
(
    id INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    registered   TIMESTAMP  DEFAULT now()   NOT NULL,
    description VARCHAR(255) NOT NULL,
    typeCurrency VARCHAR(255) NOT NULL,
    value     DOUBLE      NOT NULL,
    user_id     INTEGER      NOT NULL,
    account_id     INTEGER      NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE,
    FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE
);




